# Generated by Django 3.1.1 on 2021-03-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image_product', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id_upload', models.AutoField(primary_key=True, serialize=False)),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('prod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Remedy1.products')),
            ],
        ),
    ]
